// ══════════════════════════════════════════════
// TICKER
// ══════════════════════════════════════════════
const TICK=`
<span class="t-alert">// HARLEY SELLER BLOCKS 47TH PERSON THIS WEEK //</span>
BLACKJACK TABLE POLITELY ASKS MAN TO LEAVE (HE STAYS FOR 3RD HOUR) ·
<span class="t-alert">// CRYPTO BRO EXPLAINS BITCOIN TO WAITRESS (4TH TIME TODAY) //</span>
FB MARKETPLACE GUY SAYS "LOWEST U CAN GO?" ON A FREE ITEM ·
<span class="t-hot">// AREA MAN HITS ON 20, BUSTS, REMAINS CONFIDENT — DAY 848 //</span>
KAREN DETECTED: SECTOR 7 — NEUTRALIZATION: PENDING ·
<span class="t-alert">// PALANTIR KNOWS WHAT YOU HAD FOR BREAKFAST. IT WAS SAD. //</span>
CHEMTRAILS CONFIRMED OVER SECTOR 4 — FLUORIDE: ALREADY IN WATER ·
<span class="t-hot">// GAMER OFFERS RTX 4090 + GAMING CHAIR FOR $8,500 HARLEY. OFFER DECLINED. HE SAID "GG EZ" //</span>
HUSTLE BRO OFFERS "BRAND SYNERGY" INSTEAD OF MONEY. SELLER BLOCKED HIM. ·
<span class="t-alert">// RAYTHEON Q4 FREEDOM DELIVERY: $23.4B. YOUR SHARE: CALCULATED. //</span>
F-35 STILL BROKEN. PATCH #1,204 INCOMING. BUDGET: UNLIMITED. ETA: NEVER. ·
<span class="t-hot">// BIG YAHU: EVADING JOURNALISTS · MAGA-1: EN ROUTE TO GOLF (4TH TIME) //</span>
LOCKHEED MARTIN BILLS $2,400 FOR COFFEE MUG. CONGRESS APPROVES. ·
<span class="t-alert">// CONSPIRACY THEORIST OFFERS $350 CASH FOR $8,500 HARLEY + "WON'T TELL ANYONE WHERE YOU LIVE" //</span>
PETER THIEL REQUESTS IMMORTALITY SUBSIDY. YOUR TAX DOLLARS: ACCEPTED. ·
<span class="t-hot">// MARTINGALE STRATEGY: STILL STATISTICALLY SOUND (IT IS NOT) //</span>
REDDIT USER TIFU BY EXPLAINING MARTINGALE TO WIFE DURING THANKSGIVING. DIVORCE: IMMINENT. ·
<span class="t-alert">// BOEING LOSES ANOTHER DOOR. WHISTLEBLOWER STATUS: MANAGED. //</span>
DADA TRUMP REQUESTS $3.8B FOR GOLF + LEGAL FEES. OMNIBUS BILL: ATTACHED. ·
<span class="t-hot">// 5G SIGNAL DETECTED IN SECTOR 9 — MICROWAVE: SUSPICIOUS — ROUTER: WATCHING YOU //</span>
AREA GAMER DEMANDS 1V1 FOR HARLEY. SELLER DECLINES. GAMER SAYS "RATIO." ·
<span class="t-alert">// PLTR INTERN OFFERS $1,400 + PROMISE TO STOP MONITORING YOUR LOCATION. SELLER: STILL BLOCKING. //</span>
BLACKROCK OWNS EVERYTHING. LARRY FINK SENDS REGARDS. ·
<span class="t-hot">// ELON FIRES EVERYONE. NOTHING WORKS. INVOICE: $6.9B. EFFICIENCY: ACHIEVED. //</span>
CHECKING ACCOUNT: $3.47 · CRYPTO PORTFOLIO: $69 · STATUS: FINE ·
<span class="t-alert">// HARLEYCOIN: RUGGED · MARTINGALECOIN: RUGGED · RUGPULL.EXE: UP 999% //</span>
RENT PAID BAR: 0% · HOPIUM: 94% · DELUSION: 99% · SIGMA: DISPUTED ·
<span class="t-hot">// SHADOW BAN INCOMING · THEY ARE IN THE WALLS · TIMELINE: SHIFTED · THIS IS FINE //</span>
`.replace(/\n/g,' ');
const ti=document.getElementById('ticker-inner');
ti.innerHTML=TICK+TICK;
